package handlers

import (
	"context"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"

	"github.com/go-authgate/authgate/internal/auth"
	"github.com/go-authgate/authgate/internal/config"
	"github.com/go-authgate/authgate/internal/metrics"
	"github.com/go-authgate/authgate/internal/services"
	"github.com/go-authgate/authgate/internal/store"

	"github.com/gin-contrib/sessions"
	"github.com/gin-contrib/sessions/cookie"
	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// fakeGiteaServer returns an httptest.Server that satisfies the OAuth2 token
// exchange and Gitea userinfo endpoints needed for a full callback run.
func fakeGiteaServer(t *testing.T) *httptest.Server {
	t.Helper()
	mux := http.NewServeMux()
	mux.HandleFunc("/login/oauth/access_token", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(
			w,
			`{"access_token":"fake-access","token_type":"bearer","expires_in":3600}`,
		)
	})
	mux.HandleFunc("/api/v1/user", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(
			w,
			`{"id":42,"login":"alice","full_name":"Alice","email":"alice@example.com"}`,
		)
	})
	return httptest.NewServer(mux)
}

type oauthCallbackTestEnv struct {
	router *gin.Engine
	store  *store.Store
	server *httptest.Server
}

func setupOAuthCallbackTest(
	t *testing.T,
	rememberMeEnabled bool,
	rememberMeMaxAge int,
) *oauthCallbackTestEnv {
	t.Helper()
	gin.SetMode(gin.TestMode)

	upstream := fakeGiteaServer(t)
	t.Cleanup(upstream.Close)

	s, err := store.New(context.Background(), "sqlite", ":memory:", &config.Config{})
	require.NoError(t, err)
	userSvc := services.NewUserService(
		s, nil, nil, services.AuthModeLocal, true, services.NewNoopAuditService(), nil, 0,
	)

	provider := auth.NewGiteaProvider(auth.OAuthProviderConfig{
		ClientID:     "test-client-id",
		ClientSecret: "test-client-secret",
		RedirectURL:  "http://localhost:8080/oauth/gitea/callback",
	}, upstream.URL)

	cfg := &config.Config{
		BaseURL:                  "http://localhost:8080",
		SessionRememberMeEnabled: rememberMeEnabled,
		SessionRememberMeMaxAge:  rememberMeMaxAge,
	}
	h := NewOAuthHandler(
		map[string]*auth.OAuthProvider{"gitea": provider},
		userSvc,
		http.DefaultClient,
		cfg,
		metrics.NewNoopMetrics(),
	)

	r := gin.New()
	sessionStore := cookie.NewStore([]byte("test-secret"))
	// Use a distinct, short default MaxAge so the remember-me test can
	// distinguish the long-lived cookie (set by ApplyRememberMe) from the
	// default session cookie.
	sessionStore.Options(sessions.Options{Path: "/", MaxAge: 3600})
	r.Use(sessions.Sessions("test_session", sessionStore))
	r.GET("/oauth/:provider", h.LoginWithProvider)
	r.GET("/oauth/:provider/callback", h.OAuthCallback)
	// Exposes the session keys of interest for post-callback assertions.
	r.GET("/test-session", func(c *gin.Context) {
		sess := sessions.Default(c)
		c.JSON(http.StatusOK, gin.H{
			"oauth_redirect":    sess.Get("oauth_redirect"),
			"oauth_state":       sess.Get("oauth_state"),
			"oauth_provider":    sess.Get("oauth_provider"),
			"oauth_remember_me": sess.Get("oauth_remember_me"),
			"remember_me":       sess.Get("remember_me"),
			"user_id":           sess.Get("user_id"),
		})
	})

	return &oauthCallbackTestEnv{router: r, store: s, server: upstream}
}

// startOAuth drives LoginWithProvider and returns the state generated by the
// handler plus the session cookies that must accompany the callback request.
func startOAuth(t *testing.T, r *gin.Engine, query string) (state string, cookies []*http.Cookie) {
	t.Helper()
	req, _ := http.NewRequestWithContext(
		context.Background(),
		http.MethodGet,
		"/oauth/gitea"+query,
		nil,
	)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	require.Equal(t, http.StatusTemporaryRedirect, w.Code)

	loc, err := url.Parse(w.Header().Get("Location"))
	require.NoError(t, err)
	state = loc.Query().Get("state")
	require.NotEmpty(t, state, "state must be present in redirect URL")
	return state, sessionCookies(w)
}

// cookieByName returns the first cookie whose Name matches, or nil.
func cookieByName(cookies []*http.Cookie, name string) *http.Cookie {
	for _, c := range cookies {
		if c.Name == name {
			return c
		}
	}
	return nil
}

// TestOAuthCallback_Success_AppliesRememberMe verifies that when the user opted
// in at /oauth/:provider?remember_me=1, the callback success path applies the
// long-lived session cookie and clears the intermediate oauth_remember_me key.
func TestOAuthCallback_Success_AppliesRememberMe(t *testing.T) {
	const maxAge = 2592000 // 30 days
	env := setupOAuthCallbackTest(t, true, maxAge)

	state, loginCookies := startOAuth(t, env.router, "?remember_me=1")

	callbackReq, _ := http.NewRequestWithContext(
		context.Background(),
		http.MethodGet,
		"/oauth/gitea/callback?code=fake&state="+url.QueryEscape(state),
		nil,
	)
	for _, c := range loginCookies {
		callbackReq.AddCookie(c)
	}
	cbW := httptest.NewRecorder()
	env.router.ServeHTTP(cbW, callbackReq)
	require.Equal(t, http.StatusFound, cbW.Code,
		"callback should redirect on success; body=%s", cbW.Body.String())

	respCookies := sessionCookies(cbW)
	sessCookie := cookieByName(respCookies, "test_session")
	require.NotNil(t, sessCookie, "session cookie must be set")
	assert.Equal(t, maxAge, sessCookie.MaxAge,
		"remember-me cookie Max-Age must match SessionRememberMeMaxAge")

	sess := readSession(t, env.router, respCookies)
	assert.Equal(t, true, sess["remember_me"], "SessionRememberMe must be set on success")
	assert.Nil(t, sess["oauth_remember_me"], "oauth_remember_me must be cleared after callback")
	assert.NotNil(t, sess["user_id"], "user must be authenticated")
}

// TestOAuthCallback_Success_NoRememberMe verifies the default path leaves the
// session cookie at the default Max-Age and does not set SessionRememberMe.
func TestOAuthCallback_Success_NoRememberMe(t *testing.T) {
	const maxAge = 2592000
	env := setupOAuthCallbackTest(t, true, maxAge)

	state, loginCookies := startOAuth(t, env.router, "")

	callbackReq, _ := http.NewRequestWithContext(
		context.Background(),
		http.MethodGet,
		"/oauth/gitea/callback?code=fake&state="+url.QueryEscape(state),
		nil,
	)
	for _, c := range loginCookies {
		callbackReq.AddCookie(c)
	}
	cbW := httptest.NewRecorder()
	env.router.ServeHTTP(cbW, callbackReq)
	require.Equal(t, http.StatusFound, cbW.Code)

	respCookies := sessionCookies(cbW)
	sessCookie := cookieByName(respCookies, "test_session")
	require.NotNil(t, sessCookie)
	assert.Equal(t, 3600, sessCookie.MaxAge,
		"non-remember-me cookie must inherit the short default Max-Age")

	sess := readSession(t, env.router, respCookies)
	assert.Nil(t, sess["remember_me"], "SessionRememberMe must not be set when user did not opt in")
	assert.Nil(t, sess["oauth_remember_me"])
}
